"""Inicial migracion de vehiculos

Revision ID: 3cc36030b1ce
Revises: 
Create Date: 2025-06-27 12:40:59.951242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc36030b1ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mecanix', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('costo_reparacion', sa.Float(), nullable=True))
        batch_op.alter_column('serial',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('placas',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('placas_federales',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('combustible')
        batch_op.drop_column('eco')
        batch_op.drop_column('modelo')
        batch_op.drop_column('asientos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asientos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('modelo', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('eco', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('combustible', sa.VARCHAR(length=30), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('placas_federales',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('placas',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('serial',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('costo_reparacion')
        batch_op.drop_column('mecanix')

    # ### end Alembic commands ###
